### PR TITLE
Notice link update for England

### PR DESCRIPTION
**Pull request by marksmithtnlcf**
Updated the link within notices displayed on the dashboard. 
This was previously pointing to the top of the Emergency funding in England page, when it should be to a specific item anchor on the page.

### CODE REVIEW

**Comment by mattandrews** [comment]
Oh, you'll need to update the test snapshots as they're failing [here](https://travis-ci.com/github/biglotteryfund/blf-alpha/builds/177790909#L513). Just run this command and commit the changed file:

`npm run test-unit -- -u`

**Comment by marksmithtnlcf** [comment]
Doh! Let's try this one again 😃

**Comment by mattandrews** [comment]
Ahh the build is now failing because `npm audit` is warning of a high-severity issue with a third-party module here: https://travis-ci.com/github/biglotteryfund/blf-alpha/builds/177796546#L384

I updated that module earlier though (here: https://github.com/biglotteryfund/blf-alpha/pull/3595) so try merging `master` into this branch and seeing if the build passes then!

**Comment by mattandrews** [comment]
I've just merged `master` in here so let's see if the build passes now...

**Comment by marksmithtnlcf** [comment]
Looks like that sorted it - cheers Matt! 💯

**Pull request merged**
